### PR TITLE
Fix: children not rerendering

### LINKED ISSUE #22: Rerender swiper
Hello!
Now, if state was changed, swiper won't be changed.
Can you add this functionality, because it's really needed.
Thanks!

### PR DESCRIPTION
**Pull request by kopax**
Fix #22 #37 #50 #51

### CODE REVIEW

**Comment by kopax** [comment]
Perhaps to avoid breaking change due to hack in user land code, we should allow to disable the feature with `uniqueChildrenRender={true}` ?

**Comment by oxyii** [comment]
@kopax thank you! Let me know if @jarvisluong will not review in few days

**Comment by jarvisluong** [comment]
Looks good! Thanks for your contribution!

p/s: About the breaking change, we can release it as a minor version bump

**Comment by kopax** [comment]
@jarvisluong, If people were relying on the not rerendering behavior, then it may break their app. Since this was not a feature and this kind of integration would be incorrect, I don't think we can call it a breaking change.

Would you guys mind to publish a new version so I can get rid of the patch package?

**Comment by kopax** [comment]
Also, doc should now warn user that the `el` will now include `activeIndex` and `index`. If you guys wonder why I choose to use -1 when activeIndex - index = 0, it's for forcing a rerendering of the active view when it become active.

**Comment by kopax** [comment]
I am encountering an issue with re-rendering on an iPhone 6, within the slide I have a `LottieAnimation` and an `Animatable.View` which performs animation. It seems that the re-rendering of the active slide causes a serious lag.

This bug is possible since we allowed to re-render the active slide while displaying it. I may work on solving the issue but  any feedback on how to improve this would be appreciated.

**Pull request merged**
